[package]
name = "knock-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "knock"
path = "src/main.rs"

[dependencies]
knock-core = { path = "../knock-core" }
knock-mock = { path = "../knock-mock" }
knock-mock-adapter = { path = "../knock-mock-adapter" }
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
rpassword = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
indexmap = { workspace = true }
